const DriverBasicStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
  BLOCKED: "blocked",
};

const EntityCodeEnum = {
  DRIVER: "driver",
  USER: "user",
  USER_MEMBER: "user_member",
  HOTEL_MANAGER: "hotel_manager",
  HOTEL_BOOKING: "hotel_booking",
  BUS_OPERATOR: "bus_operator",
  BUS_MEMBER: "bus_member",
  BUS_BOOKING: "bus_booking",
  ADMIN: "admin",
  RIDES: "rides",
  BUSDRIVER: "busDriver",
};

const GenderEnum = {
  MALE: "male",
  FEMALE: "female",
};

const DriverDocEnum = {
  IDCARD: "id_card",
  LICENSE: "license",
  INSURANCE: "insurance",
  REGISTRATION: "registration",
  VEHICLEPHOTO: "vehicle_photo",
  PASSBOOK: "passbook",
  AVATAR: "avatar",
};

const DriverDocStatusEnum = {
  PENDING: "pending",
  APPROVED: "approved",
  REJECTED: "rejected",
};

const VehicleTypeEnum = {
  TAXI: "taxi",
  BIKE: "bike",
};

const TicketStatusEnum = {
  OPEN: "open",
  INPROGRESS: "in_progress",
  CLOSED: "closed",
};

const RideBookStatusEnum = {
  REQUESTED: "requested",
  RECEIVED: "received",
  ACCEPTED: "accepted",
  REJECTED: "rejected",
  ARRIVED: "arrived",
  STARTED: "started",
  COMPLETED: "completed",
  CANCELLED: "cancelled",
  ONGOING: "ongoing",
};

const PaymentStatusEnum = {
  PENDING: "PENDING",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
};

const LocationStatusEnum = {
  ONLINE: "online",
  OFFLINE: "offline",
  ONTRIP: "on_trip",
};

const BookCancelledByEnum = {
  DRIVER: "driver",
  USER: "user",
  SYSTEM: "system",
};

const TransactionTypeEnum = {
  CREDIT: "CREDIT",
  DEBIT: "DEBIT",
};

const WalletCurrencyEnum = {
  XAF: "XAF",
  USD: "USD",
  EUR: "EUR",
  INR: "INR",
};

const CommissionServiceTypeEnum = {
  USER: "user",
  PLATFORM: "platform",
  BUS: "bus",
  HOTEL: "hotel",
  TAXI: "taxi",
  BIKE: "bike",
};

const CommissionTypeEnum = {
  PERCENTAGE: "percentage",
  FIXED: "fixed",
};

const CommissionStatusEnum = {
  ACTIVE: "active",
  INACTIVE: "in_active",
};

const NotificationTypeEnum = {
  TAXI_DRIVER_REGISTERED: "TAXI_DRIVER_REGISTERED",
  BIKE_DRIVER_REGISTERED: "BIKE_DRIVER_REGISTERED",
  USER_REGISTERED: "USER_REGISTERED",
  BUS_OPERATOR_REGISTERED: "BUS_OPERATOR_REGISTERED",
  HOTEL_MANAGER_REGISTERED: "HOTEL_MANAGER_REGISTERED",
};
const NationalityEnum = {
  AFGHAN: "Afghan",
  ALBANIAN: "Albanian",
  ALGERIAN: "Algerian",
  AMERICAN: "American",
  ANDORRAN: "Andorran",
  ANGOLAN: "Angolan",
  ANTIGUAN_OR_BARBUDAN: "Antiguan or Barbudan",
  ARGENTINE: "Argentine",
  ARMENIAN: "Armenian",
  AUSTRALIAN: "Australian",
  AUSTRIAN: "Austrian",
  AZERBAIJANI: "Azerbaijani",
  BAHAMIAN: "Bahamian",
  BAHRAINI: "Bahraini",
  BANGLADESHI: "Bangladeshi",
  BARBADIAN: "Barbadian",
  BELARUSIAN: "Belarusian",
  BELGIAN: "Belgian",
  BELIZEAN: "Belizean",
  BENINESE: "Beninese",
  BHUTANESE: "Bhutanese",
  BOLIVIAN: "Bolivian",
  BOSNIAN: "Bosnian",
  BOTSWANAN: "Botswanan",
  BRAZILIAN: "Brazilian",
  BRITISH: "British",
  BRUNEIAN: "Bruneian",
  BULGARIAN: "Bulgarian",
  BURKINABE: "Burkinabe",
  BURMESE: "Burmese",
  BURUNDIAN: "Burundian",
  CAMBODIAN: "Cambodian",
  CAMEROONIAN: "Cameroonian",
  CANADIAN: "Canadian",
  CAPE_VERDEAN: "Cape Verdean",
  CENTRAL_AFRICAN: "Central African",
  CHADIAN: "Chadian",
  CHILEAN: "Chilean",
  CHINESE: "Chinese",
  COLOMBIAN: "Colombian",
  COMORAN: "Comoran",
  CONGOLESE: "Congolese",
  COSTA_RICAN: "Costa Rican",
  CROATIAN: "Croatian",
  CUBAN: "Cuban",
  CYPRIOT: "Cypriot",
  CZECH: "Czech",
  DANISH: "Danish",
  DJIBOUTIAN: "Djiboutian",
  DOMINICAN: "Dominican",
  DUTCH: "Dutch",
  EAST_TIMORESE: "East Timorese",
  ECUADORIAN: "Ecuadorian",
  EGYPTIAN: "Egyptian",
  EMIRATI: "Emirati",
  ENGLISH: "English",
  EQUATORIAL_GUINEAN: "Equatorial Guinean",
  ERITREAN: "Eritrean",
  ESTONIAN: "Estonian",
  ETHIOPIAN: "Ethiopian",
  FIJIAN: "Fijian",
  FILIPINO: "Filipino",
  FINNISH: "Finnish",
  FRENCH: "French",
  GABONESE: "Gabonese",
  GAMBIAN: "Gambian",
  GEORGIAN: "Georgian",
  GERMAN: "German",
  GHANAIAN: "Ghanaian",
  GREEK: "Greek",
  GRENADIAN: "Grenadian",
  GUATEMALAN: "Guatemalan",
  GUINEAN: "Guinean",
  GUINEA_BISSAUAN: "Guinea-Bissauan",
  GUYANESE: "Guyanese",
  HAITIAN: "Haitian",
  HONDURAN: "Honduran",
  HUNGARIAN: "Hungarian",
  ICELANDIC: "Icelandic",
  INDIAN: "Indian",
  INDONESIAN: "Indonesian",
  IRANIAN: "Iranian",
  IRAQI: "Iraqi",
  IRISH: "Irish",
  ISRAELI: "Israeli",
  ITALIAN: "Italian",
  IVORIAN: "Ivorian",
  JAMAICAN: "Jamaican",
  JAPANESE: "Japanese",
  JORDANIAN: "Jordanian",
  KAZAKH: "Kazakh",
  KENYAN: "Kenyan",
  KIRIBATI: "Kiribati",
  KOREAN: "Korean",
  KUWAITI: "Kuwaiti",
  KYRGYZ: "Kyrgyz",
  LAOTIAN: "Laotian",
  LATVIAN: "Latvian",
  LEBANESE: "Lebanese",
  LIBERIAN: "Liberian",
  LIBYAN: "Libyan",
  LIECHTENSTEINER: "Liechtensteiner",
  LITHUANIAN: "Lithuanian",
  LUXEMBOURGER: "Luxembourger",
  MACEDONIAN: "Macedonian",
  MALAGASY: "Malagasy",
  MALAWIAN: "Malawian",
  MALAYSIAN: "Malaysian",
  MALDIVIAN: "Maldivian",
  MALIEN: "Malien",
  MALTESE: "Maltese",
  MARSHALLESE: "Marshallese",
  MAURITANIAN: "Mauritanian",
  MAURITIAN: "Mauritian",
  MEXICAN: "Mexican",
  MICRONESIAN: "Micronesian",
  MOLDOVAN: "Moldovan",
  MONACAN: "Monacan",
  MONGOLIAN: "Mongolian",
  MONTENEGRIN: "Montenegrin",
  MOROCCAN: "Moroccan",
  MOZAMBICAN: "Mozambican",
  NAMIBIAN: "Namibian",
  NAURUAN: "Nauruan",
  NEPALESE: "Nepalese",
  NEW_ZEALANDER: "New Zealander",
  NICARAGUAN: "Nicaraguan",
  NIGERIAN: "Nigerian",
  NORWEGIAN: "Norwegian",
  OMANI: "Omani",
  PAKISTANI: "Pakistani",
  PALAUAN: "Palauan",
  PALESTINIAN: "Palestinian",
  PANAMANIAN: "Panamanian",
  PAPUA_NEW_GUINEAN: "Papua New Guinean",
  PARAGUAYAN: "Paraguayan",
  PERUVIAN: "Peruvian",
  POLISH: "Polish",
  PORTUGUESE: "Portuguese",
  QATARI: "Qatari",
  ROMANIAN: "Romanian",
  RUSSIAN: "Russian",
  RWANDAN: "Rwandan",
  SAINT_LUCIAN: "Saint Lucian",
  SAMOAN: "Samoan",
  SAN_MARINESE: "San Marinese",
  SAO_TOMEAN: "Sao Tomean",
  SAUDI: "Saudi",
  SCOTTISH: "Scottish",
  SENEGALESE: "Senegalese",
  SERBIAN: "Serbian",
  SEYCHELLOIS: "Seychellois",
  SIERRA_LEONEAN: "Sierra Leonean",
  SINGAPOREAN: "Singaporean",
  SLOVAK: "Slovak",
  SLOVENIAN: "Slovenian",
  SOLOMON_ISLANDER: "Solomon Islander",
  SOMALI: "Somali",
  SOUTH_AFRICAN: "South African",
  SOUTH_KOREAN: "South Korean",
  SPANISH: "Spanish",
  SRI_LANKAN: "Sri Lankan",
  SUDANESE: "Sudanese",
  SURINAMESE: "Surinamese",
  SWAZI: "Swazi",
  SWEDISH: "Swedish",
  SWISS: "Swiss",
  SYRIAN: "Syrian",
  TAIWANESE: "Taiwanese",
  TAJIK: "Tajik",
  TANZANIAN: "Tanzanian",
  THAI: "Thai",
  TOGOLESE: "Togolese",
  TONGAN: "Tongan",
  TRINIDADIAN_OR_TOBAGONIAN: "Trinidadian or Tobagonian",
  TUNISIAN: "Tunisian",
  TURKISH: "Turkish",
  TURKMEN: "Turkmen",
  TUVALUAN: "Tuvaluan",
  UGANDAN: "Ugandan",
  UKRAINIAN: "Ukrainian",
  URUGUAYAN: "Uruguayan",
  UZBEK: "Uzbek",
  VENEZUELAN: "Venezuelan",
  VIETNAMESE: "Vietnamese",
  WELSH: "Welsh",
  YEMENI: "Yemeni",
  ZAMBIAN: "Zambian",
  ZIMBABWEAN: "Zimbabwean",
  OTHER: "Other (Specify)",
};

module.exports = {
  NationalityEnum,
  NotificationTypeEnum,
  DriverBasicStatus,
  EntityCodeEnum,
  GenderEnum,
  DriverDocEnum,
  DriverDocStatusEnum,
  VehicleTypeEnum,
  TicketStatusEnum,
  RideBookStatusEnum,
  PaymentStatusEnum,
  LocationStatusEnum,
  BookCancelledByEnum,
  TransactionTypeEnum,
  WalletCurrencyEnum,
  CommissionServiceTypeEnum,
  CommissionTypeEnum,
  CommissionStatusEnum,
};
