version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    container_name: wemove
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - "8001:8000"
    networks:
      - wemove-network
    # restart: unless-stopped

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - wemove-network
    # restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 10s
      timeout: 5s
      retries: 5


  redis:
    image: redis:7
    container_name: wemove-redis
    ports:
      - "6379:6379"    
    volumes:
      - redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - wemove-network
    restart: unless-stopped
    


volumes:
  mongo-data:
  redis-data:

networks:
  wemove-network:
    name: services_wemove-network 
