require("dotenv").config();

const port = process.env.PORT || 8000;

module.exports = {
  port: port,
  mongodb_url: process.env.MONGODB_URI,
  allowed_origin: process.env.CORS_ORIGIN,
  node_env: process.env.NODE_ENV,
  hash_rounds: process.env.HASH_ROUNDS,
  access_token_secret: process.env.ACCESS_TOKEN_SECRET,
  refresh_token_secret: process.env.REFRESH_TOKEN_SECRET,
  access_token_expiration_time: process.env.ACCESS_TOKEN_EXPIRATION,
  refresh_token_expiration_time: process.env.REFRESH_TOKEN_EXPIRATION,
  cloud_name: process.env.CLOUD_NAME,
  cloud_api_key: process.env.CLOUD_API_KEY,
  cloud_api_secret: process.env.CLOUD_API_SECRET,
  email_user: process.env.EMAIL_USER,
  email_from: process.env.EMAIL_FROM,
  email_pass: process.env.EMAIL_PASS,
  smtp_service: process.env.SMTP_SERVICE,
  smtp_port: process.env.SMTP_PORT,
  smtp_host: process.env.SMTP_HOST,
  google_maps_api_key: process.env.GOOGLE_MAPS_API_KEY,
  redis_host: process.env.REDIS_HOST,
  redis_port: process.env.REDIS_PORT,
  momo_callback_url: process.env.MOMO_CALLBACK_URL,
  momo_target_environment: process.env.MOMO_TARGET_ENVIRONMENT,
  momo_base_url: process.env.MOMO_BASE_URL,
  momo_collection_primary_key: process.env.MOMO_COLLECTION_PRIMARY_KEY,
  momo_disbursement_primary_key: process.env.MOMO_DISBURSEMENT_PRIMARY_KEY,
  momo_collection_user_id: process.env.MOMO_COLLECTION_USER_ID,
  momo_disbursement_user_id: process.env.MOMO_DISBURSEMENT_USER_ID,
  momo_collection_api_key: process.env.MOMO_COLLECTION_API_KEY,
  momo_disbursement_api_key: process.env.MOMO_DISBURSEMENT_API_KEY,
  aws_region: process.env.AWS_REGION,
  aws_access_key_id: process.env.AWS_ACCESS_KEY_ID,
  aws_secret_access_key: process.env.AWS_SECRET_ACCESS_KEY,
  aws_bucket_name: process.env.AWS_BUCKET_NAME,
  twilio_account_sid: process.env.TWILIO_ACCOUNT_SID,
  twilio_auth_token: process.env.TWILIO_AUTH_TOKEN,
  twilio_phone_number: process.env.TWILIO_PHONE_NUMBER,
  cameroon_country_code: process.env.CAMEROON_COUNTRY_CODE,
  superadmin_email: process.env.SUPERADMIN_EMAIL,
  superadmin_username: process.env.SUPERADMIN_USERNAME,
  superadmin_password: process.env.SUPERADMIN_PASSWORD,
  superadmin_phone: process.env.SUPERADMIN_PHONE,

  do_access_key: process.env.DO_ACCESS_KEY,
  do_secret_key: process.env.DO_SECRET_KEY,
  do_endpoint: process.env.DO_ENDPOINT,
  do_bucket_name: process.env.DO_BUCKET_NAME,
  sms_sender: process.env.SMS_SENDER,
};
